export const TX_TYPE = {
  DEPOSIT: "DEPOSIT",
  WITHDRAW: "WITHDRAW",
  TRANSFER: "TRANSFER",
};

export const TX_STATUS = {
  REQUESTED: "REQUESTED",
  COMMITED: "COMMITED",
  CANCELED: "CANCELED",
};
