export const TX_TYPE = {
  DEPOSIT: "DEPOSIT",
  WITHDRAW: "WITHDRAW",
  TRANSFER: "TRANSFER",
  WITHDRAW_TO_BANK: "WITHDRAW_TO_BANK",
  DEPOSIT_FROM_WALLET: "DEPOSIT_FROM_WALLET",
};

export const TX_STATUS = {
  REQUESTED: "REQUESTED",
  COMMITED: "COMMITED",
  CANCELED: "CANCELED",
};
